# Generated by Django 4.0.5 on 2022-07-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
