# Generated by Django 4.0.5 on 2022-07-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_sales_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticides',
            name='plant',
        ),
        migrations.AddField(
            model_name='pesticides',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.plant'),
        ),
    ]
